### ISSUE TITLE
[scroll area] Need a styling attribute to check for overflow presence

### ISSUE THREAD

**Issue by vladmoroz** [mui/base-ui#1100]
# Feature request

I attempted styling ScrollArea with a hard scrollbar and ended up with a selector that looked like this:
```css
  .ScrollAreaViewport {
    height: 100%;

    &:has(+ .ScrollAreaScrollbar[data-orientation='horizontal']) {
      padding-bottom: 1.5rem;
    }
}
```

I think we need data attributes both on Root and Viewport to target this comfortably.

Naming ideas:
- `data-has-overflow-x` / `data-has-overflow-y`
- `data-has-vertical-scrollbar` / `data-has-horizontal-scrollbar`
