### ISSUE TITLE
[Select] Keep focus indicator on trigger when popup is open

### ISSUE THREAD

**Issue by tomshane** [mui/base-ui#1761]
# Feature request

## Summary

Currently, when popup is open, the trigger loses focus. I need to keep trigger indicating it is focused (with outline) on popup open. It doesn't have to maintain "physical" focus, just some data-attribute could be handy to style the trigger properly.

I have made some workarounds using onOpenChangeComplete, but the trigger outline still flickers, when using transitions and animations when closing popup.

https://github.com/user-attachments/assets/daca159b-898e-42b4-8d3b-d0430ee8a5b9

**Comment by atomiks** [comment]
Does `[data-popup-open]` on the trigger work?

**Comment by tomshane** [comment]
> Does `[data-popup-open]` on the trigger work?

It does, but it is removed immediately when the popup starts closing. So when transition is used on the popup, trigger didn't received focus yet and the data-popup-open is already gone, causing the flicker similar to what is displayed in the video.

**Comment by atomiks** [comment]
Using `onOpenChangeComplete` to set `data-popup-mounted` as a new attribute seems to avoid the flicker here: https://codesandbox.io/p/sandbox/affectionate-frost-84w7mr?file=%2Fsrc%2Findex.module.css%3A21%2C1-29%2C4

```jsx
  const [mounted, setMounted] = React.useState(false);

  return (
    <Select.Root
      defaultValue="sans"
      alignItemToTrigger={false}
      onOpenChangeComplete={setMounted}
    >
      <Select.Trigger
        className={styles.Select}
        data-popup-mounted={mounted ? "" : undefined}
      >
```

```css
  outline: 2px solid transparent;
  transition: outline 0.2s;
  outline-offset: -1px;

  &[data-popup-open],
  &[data-popup-mounted],
  &:focus {
    outline: 2px solid var(--color-blue);
  }
```
