### ISSUE TITLE
Layout shift when opening menu due to `body` width changes

### ISSUE THREAD

**Issue by OliverJAsh** [mui/base-ui#2077]
# Bug report

## Current behavior

When the menu is opened, the `body` width changes, resulting in a layout shift (notice how the text no longer wraps):

https://github.com/user-attachments/assets/b26d2201-6c0c-4db9-9b42-0a2b91b9565b

## Expected behavior

The `body` width should not change when the menu is opened.

## Reproducible example

https://codesandbox.io/p/devbox/laughing-panini-2r7nzn?file=%2Fsrc%2FApp.tsx&workspaceId=ws_4qKVDKGuRrrvd8oLfoRWSz

## Base UI version

1.0.0-beta.0

## Which browser are you using?

Chrome

## Which OS are you using?

Mac OS

Make sure "Show scroll bars" macOS setting is set to "Always".

## Which assistive tech are you using (if applicable)?

N/A

## Additional context

In this example, we have the following CSS to prevent scrolling the background when a native modal `<dialog>` is open on the page:

```css
html {
  /* Prevent layout shift when opening the modal dialog */
  scrollbar-gutter: stable;
}


/* Remove scroll on the root container when the modal dialog is open. */
html:has(.modalDialog) {
  overflow: hidden;
}
```

I noticed that Base UI sets an explicit width on the `body` when the menu is opened. I suspsect this width is supposed to match the `body`'s natural width before the menu was opened. If that's the case, it seems there's a bug in the logic to calculate the `body` width in that it's not accounting for `overflow: hidden` and `scrollbar-gutter: stable` on `html`.

If it helps, [here is a contrived example](https://codesandbox.io/p/devbox/modest-kate-vlycdy?file=%2Fsrc%2FApp.tsx&workspaceId=ws_4qKVDKGuRrrvd8oLfoRWSz) that doesn't use `<dialog>` at all. All that's needed to reproduce the problem is to define this CSS:

```css
html {
  scrollbar-gutter: stable;
  overflow: hidden;
}
```

https://github.com/user-attachments/assets/05d6178f-84a4-4b1c-8d29-6e064e07f1ed
