### ISSUE TITLE
[slider] Remove data-orientation="horizontal" duplication

### ISSUE THREAD

**Issue by oliviertassinari** [mui/base-ui#625]
### Summary

Open https://master--base-ui.netlify.app/components/react-slider/ see `data-orientation="horizontal"` 4 times in the DOM notes

<img width="1032" alt="SCR-20240916-uhfe" src="https://github.com/user-attachments/assets/a94eea45-51c7-4f33-ae8e-5e4458b3ed76">

I'm confused, why is this not only once on the root DOM node and people use parent CSS selectors to write the CSS?

**Search keywords**: -

**Comment by colmtuite** [comment]
Why would you want to have to use `:has()` or descendant selectors?

It's generally a bad idea to have your styles rely on DOM structure. It will of course be fine in this specific example, but it's a bad practice. `:has()` and descendant selectors are less ergonomic and add noise. Especially with CSS-in-JS, syntax can get a little gnarly. It's standard practice in the space to provide style hooks per component.

**Comment by oliviertassinari** [comment]
> Why would you want to have to use :has() or descendant selectors?

@colmtuite I would imagine that we could have one `data-orientation="horizontal"` attribute on the root. In this configuration, developers would write CSS that looks like:

```css
/* root */
.Slider {
  color: red;

  &[data-orientation="vertical"] {
    color: blue;
  }
}

/* thumb */
.Slider-thumb {
  background-color: red;

  [data-orientation="vertical"] & {
    background-color: blue;
  }
}
```

I don't see how `:has()` applies here.

With CSS-in-JS:

```jsx
const SliderRoot = styled(SliderBase.Root)(`
  color: red;

  &[data-orientation="vertical"] {
    color: blue;
  }
`);

const SliderThumb = styled(SliderBase.Thumb)(`
  background-color: red;

  [data-orientation="vertical"] & {
    background-color: blue;
  }
`);
```

It feels like this duplication makes it harder to read the DOM in the dev tools to figure out what can be used for customization. On the opposite side, I don't really see the added value of the duplication.
