### ISSUE TITLE
[ScrollArea] Make it possible to recreate the macOS overlay scrollbar behaviour

### ISSUE THREAD

**Issue by vladmoroz** [mui/base-ui#982]
I've tried to recreate how the macOS overlay scrollbar works, but couldn't.

Mainly, it's shown when scrolling, and once shown, it persists if the cursor is placed over the scrollbar itself in time before it hides—we don't have a style hook for this, nor it seems to be possible with CSS

**Search keywords**:

**Comment by atomiks** [comment]
> we don't have a style hook for this, nor it seems to be possible with CSS

The original demo on `components/react-scroll-area` does this though? It uses `:hover` on the `Scrollbar` part itself to persist it.

```css
  &[data-hovering],
  &[data-scrolling],
  &:hover {
    visibility: visible;
    opacity: 1;
  }

  &[data-scrolling]:not(:hover) {
    transition: none;
  }
```
